# Generated by Django 5.1.4 on 2025-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0004_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5),
        ),
    ]
