# Generated by Django 5.1.4 on 2025-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0005_event_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_user',
            field=models.BooleanField(default=False),
        ),
    ]
